const crypto=require('crypto');
const {
  supabase,json,getBody,safeName,requireAdmin,requireProcessor,safeEqual,
  signAdmin,publicObjectUrl,siteUrl,allowMethod
}=require('../lib/server');

function routeName(req){
  const raw=Array.isArray(req.query?.route)?req.query.route.join('/'):(req.query?.route||'');
  return String(raw).replace(/^\/+|\/+$/g,'');
}

async function authLogin(req,res){
  if(!allowMethod(req,res,['POST']))return;
  const b=getBody(req);
  if(!safeEqual(String(b.username||'').toLowerCase(),String(process.env.ADMIN_USERNAME||'admin').toLowerCase())||!safeEqual(b.password,process.env.ADMIN_PASSWORD||''))return json(res,401,{message:'Sai tài khoản hoặc mật khẩu Admin.'});
  const token=signAdmin();
  res.setHeader('Set-Cookie',`vatly_admin=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`);
  return json(res,200,{ok:true,username:process.env.ADMIN_USERNAME||'admin'});
}
async function authLogout(req,res){if(!allowMethod(req,res,['POST']))return;res.setHeader('Set-Cookie','vatly_admin=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');return json(res,200,{ok:true})}
async function health(req,res){if(!allowMethod(req,res,['GET']))return;try{const s=supabase();const {data,error}=await s.from('processor_workers').select('last_seen_at,worker_name').order('last_seen_at',{ascending:false}).limit(1);if(error)throw error;const last=data?.[0]||null,online=!!(last&&Date.now()-new Date(last.last_seen_at).getTime()<120000);return json(res,200,{status:'Vercel + Supabase online',processor_online:online,worker:last?.worker_name||null,last_seen_at:last?.last_seen_at||null})}catch(e){return json(res,500,{status:'Lỗi cấu hình',message:e.message})}}
async function createUpload(req,res){if(!allowMethod(req,res,['POST'])||!requireAdmin(req,res))return;try{const b=getBody(req),name=String(b.file_name||''),ext=(name.split('.').pop()||'').toLowerCase(),max=(Number(process.env.MAX_UPLOAD_MB)||100)*1024*1024;if(!['docx','pdf'].includes(ext))return json(res,400,{message:'Chỉ nhận .docx hoặc .pdf.'});if(Number(b.file_size||0)<=0||Number(b.file_size)>max)return json(res,400,{message:`Dung lượng không hợp lệ hoặc vượt ${Math.round(max/1024/1024)} MB.`});if(!b.lesson_id)return json(res,400,{message:'Thiếu lesson_id.'});const s=supabase(),sourceId=crypto.randomUUID(),jobId=crypto.randomUUID(),path=`${b.lesson_id}/${sourceId}/${safeName(name)}`;const {data:up,error:ue}=await s.storage.from('lesson-originals').createSignedUploadUrl(path);if(ue)throw ue;const src={id:sourceId,lesson_id:b.lesson_id,lesson_title:b.lesson_title||b.lesson_id,grade:Number(b.grade)||null,chapter:Number(b.chapter)||null,lesson_number:Number(b.lesson_number)||null,original_name:name,mime_type:b.mime_type||'',size_bytes:Number(b.file_size)||0,storage_path:path,status:'uploading'};let q=await s.from('source_documents').insert(src);if(q.error)throw q.error;const job={id:jobId,source_id:sourceId,lesson_id:b.lesson_id,lesson_title:b.lesson_title||b.lesson_id,grade:Number(b.grade)||null,chapter:Number(b.chapter)||null,lesson_number:Number(b.lesson_number)||null,status:'uploading',stage:'upload',stage_label:'Đang tải file',progress:0,message:'Đang tải file gốc lên Supabase Storage',options:b.options||{},requested_publish_path:b.publish_path||''};q=await s.from('processing_jobs').insert(job);if(q.error)throw q.error;return json(res,200,{job_id:jobId,source_id:sourceId,status:'uploading',signed_upload_url:up.signedUrl,upload_token:up.token,storage_path:path})}catch(e){return json(res,500,{message:e.message})}}
async function completeUpload(req,res){if(!allowMethod(req,res,['POST'])||!requireAdmin(req,res))return;try{const b=getBody(req),s=supabase();if(!b.job_id)return json(res,400,{message:'Thiếu job_id.'});const now=new Date().toISOString();let q=await s.from('processing_jobs').update({status:'queued',stage:'upload',stage_label:'Đã tải file • chờ Windows Processor',progress:5,message:'File đã lưu an toàn. Đang chờ máy Windows nhận việc.',updated_at:now}).eq('id',b.job_id).eq('source_id',b.source_id);if(q.error)throw q.error;q=await s.from('source_documents').update({status:'uploaded',updated_at:now}).eq('id',b.source_id);if(q.error)throw q.error;return json(res,200,{ok:true,status:'queued'})}catch(e){return json(res,500,{message:e.message})}}
async function job(req,res){if(!allowMethod(req,res,['GET'])||!requireAdmin(req,res))return;try{const id=String(req.query.id||'');const s=supabase();const {data,error}=await s.from('processing_jobs').select('*').eq('id',id).single();if(error)throw error;return json(res,200,{...data,job_id:data.id,source_name:data.source_name||undefined})}catch(e){return json(res,404,{message:'Không tìm thấy job: '+e.message})}}
async function lesson(req,res){if(!allowMethod(req,res,['GET']))return;try{const s=supabase();const {data,error}=await s.from('lessons').select('lesson_id,title,published,storage_url,publish_url').eq('lesson_id',String(req.query.lesson_id||'')).single();if(error||!data?.published)return json(res,404,{message:'Bài học chưa được xuất bản.'});return json(res,200,data)}catch(e){return json(res,404,{message:'Bài học chưa được xuất bản.'})}}
async function lessons(req,res){if(!allowMethod(req,res,['GET'])||!requireAdmin(req,res))return;try{const s=supabase(),grade=Number(req.query.grade||0);let q=s.from('lessons').select('*').order('lesson_number',{ascending:true});if(grade)q=q.eq('grade',grade);const {data,error}=await q;if(error)throw error;const out=[];for(const l of data||[]){let j=null;if(l.current_job_id){const r=await s.from('processing_jobs').select('*').eq('id',l.current_job_id).maybeSingle();j=r.data?{...r.data,job_id:r.data.id}:null}out.push({...l,job:j})}return json(res,200,{lessons:out})}catch(e){return json(res,500,{message:e.message})}}
async function review(req,res){if(!allowMethod(req,res,['GET'])||!requireAdmin(req,res))return;try{const s=supabase();const {data,error}=await s.from('review_items').select('*').eq('job_id',String(req.query.job_id||'')).eq('resolved',false).order('created_at',{ascending:true});if(error)throw error;return json(res,200,{items:data||[]})}catch(e){return json(res,500,{message:e.message})}}
async function reviewResolve(req,res){if(!allowMethod(req,res,['POST'])||!requireAdmin(req,res))return;try{const b=getBody(req),s=supabase();const {data:item,error:e1}=await s.from('review_items').update({resolved:true,resolved_at:new Date().toISOString()}).eq('id',b.item_id).select('job_id').single();if(e1)throw e1;const {data:open,error:e2}=await s.from('review_items').select('id,severity').eq('job_id',item.job_id).eq('resolved',false);if(e2)throw e2;const blocking=(open||[]).filter(x=>x.severity==='error').length;await s.from('processing_jobs').update({review_count:(open||[]).length,blocking_issues:blocking,status:(open||[]).length?'needs_review':'ready',updated_at:new Date().toISOString()}).eq('id',item.job_id);return json(res,200,{ok:true,review_count:(open||[]).length,blocking_issues:blocking})}catch(e){return json(res,500,{message:e.message})}}
async function publish(req,res){if(!allowMethod(req,res,['POST'])||!requireAdmin(req,res))return;try{const b=getBody(req),s=supabase();const {data:j,error:je}=await s.from('processing_jobs').select('*').eq('id',b.job_id).eq('lesson_id',b.lesson_id).single();if(je)throw je;if(!['ready','needs_review'].includes(j.status))return json(res,409,{message:'Job chưa sẵn sàng để xuất bản.'});if(Number(j.blocking_issues||0)>0)return json(res,409,{message:`Còn ${j.blocking_issues} lỗi mức chặn.`});if(!j.preview_path)return json(res,409,{message:'Chưa có bản Preview.'});const target=`published/${b.lesson_id}/${j.id}/index.html`;const cp=await s.storage.from('lesson-public').copy(j.preview_path,target);if(cp.error)throw cp.error;const storageUrl=publicObjectUrl('lesson-public',target),site=siteUrl(`/lesson.html?id=${encodeURIComponent(b.lesson_id)}`),now=new Date().toISOString();const lessonRow={lesson_id:b.lesson_id,title:j.lesson_title||b.lesson_id,grade:j.grade,chapter:j.chapter,lesson_number:j.lesson_number,published:true,publish_url:site,storage_url:storageUrl,preview_url:j.preview_url,current_job_id:j.id,updated_at:now};let q=await s.from('lessons').upsert(lessonRow,{onConflict:'lesson_id'});if(q.error)throw q.error;q=await s.from('processing_jobs').update({status:'published',published:true,publish_url:site,storage_url:storageUrl,progress:100,stage:'preview',stage_label:'Đã xuất bản',message:'Bài học đã được xuất bản.',updated_at:now}).eq('id',j.id);if(q.error)throw q.error;return json(res,200,{publish_url:site,storage_url:storageUrl,job:{...j,status:'published',published:true,publish_url:site,progress:100}})}catch(e){return json(res,500,{message:e.message})}}
async function processorClaim(req,res){if(!allowMethod(req,res,['GET'])||!requireProcessor(req,res))return;try{const s=supabase();const stale=new Date(Date.now()-45*60*1000).toISOString();await s.from('processing_jobs').update({status:'queued',stage:'parse',stage_label:'Tự động xếp hàng lại sau khi Processor gián đoạn',message:'Job được xếp hàng lại vì lần xử lý trước mất kết nối.',worker_name:null,claimed_at:null,updated_at:new Date().toISOString()}).eq('status','processing').lt('updated_at',stale);const {data:list,error}=await s.from('processing_jobs').select('*').eq('status','queued').order('created_at',{ascending:true}).limit(1);if(error)throw error;if(!list?.length)return json(res,200,null);const j=list[0],worker=String(req.headers['x-worker-name']||'Windows-Processor'),now=new Date().toISOString();const up=await s.from('processing_jobs').update({status:'processing',stage:'parse',stage_label:'Windows Processor đã nhận việc',progress:8,worker_name:worker,claimed_at:now,updated_at:now}).eq('id',j.id).eq('status','queued').select('*').maybeSingle();if(up.error)throw up.error;if(!up.data)return json(res,200,null);const {data:src,error:se}=await s.from('source_documents').select('*').eq('id',j.source_id).single();if(se)throw se;const {data:sign,error:sige}=await s.storage.from('lesson-originals').createSignedUrl(src.storage_path,3600);if(sige)throw sige;return json(res,200,{...up.data,job_id:up.data.id,source_id:src.id,original_name:src.original_name,source_size:src.size_bytes,source_type:src.mime_type,source_url:sign.signedUrl})}catch(e){return json(res,500,{message:e.message})}}
async function processorHeartbeat(req,res){if(!allowMethod(req,res,['POST'])||!requireProcessor(req,res))return;try{const b=getBody(req),worker=String(req.headers['x-worker-name']||b.worker_name||'Windows-Processor'),s=supabase();const row={worker_name:worker,host_name:String(req.headers['x-worker-host']||''),version:b.version||'',current_job_id:b.current_job_id||null,last_seen_at:new Date().toISOString(),note:b.note||''};const {error}=await s.from('processor_workers').upsert(row,{onConflict:'worker_name'});if(error)throw error;return json(res,200,{ok:true})}catch(e){return json(res,500,{message:e.message})}}
async function processorProgress(req,res){if(!allowMethod(req,res,['POST'])||!requireProcessor(req,res))return;try{const b=getBody(req),s=supabase();const patch={stage:b.stage||'parse',stage_label:b.stage_label||'',progress:Math.max(0,Math.min(99,Number(b.progress)||0)),message:b.message||'',updated_at:new Date().toISOString()};const {error}=await s.from('processing_jobs').update(patch).eq('id',b.job_id);if(error)throw error;return json(res,200,{ok:true})}catch(e){return json(res,500,{message:e.message})}}
async function processorResultUpload(req,res){if(!allowMethod(req,res,['POST'])||!requireProcessor(req,res))return;try{const b=getBody(req),id=String(b.job_id||''),s=supabase();if(!id)return json(res,400,{message:'Thiếu job_id.'});const specs=[['html',`previews/${id}/index.html`],['json',`results/${id}/result.json`]];if(b.has_pdf)specs.push(['pdf',`previews/${id}/document.pdf`]);const uploads={};for(const [key,path] of specs){const {data,error}=await s.storage.from('lesson-public').createSignedUploadUrl(path,{upsert:true});if(error)throw error;uploads[key]={path,token:data.token,signed_url:data.signedUrl,public_url:publicObjectUrl('lesson-public',path)}}return json(res,200,{uploads})}catch(e){return json(res,500,{message:e.message})}}
async function processorComplete(req,res){if(!allowMethod(req,res,['POST'])||!requireProcessor(req,res))return;try{const b=getBody(req),id=String(b.job_id||''),s=supabase(),issues=Array.isArray(b.issues)?b.issues:[],report=b.report||{};if(!id||!b.preview_path)return json(res,400,{message:'Thiếu job_id hoặc preview_path.'});await s.from('review_items').delete().eq('job_id',id);if(issues.length){const rows=issues.map((x,i)=>({job_id:id,severity:x.severity||'warning',type:x.type||x.category||'review',category:x.category||x.type||'review',message:String(x.message||''),source_ref:x.source_ref||'',preview_url:b.preview_url||publicObjectUrl('lesson-public',b.preview_path),sort_order:i+1,resolved:false}));const q=await s.from('review_items').insert(rows);if(q.error)throw q.error}const reviewCount=issues.length,blocking=issues.filter(x=>x.severity==='error').length,status=reviewCount?'needs_review':'ready',previewUrl=b.preview_url||publicObjectUrl('lesson-public',b.preview_path),now=new Date().toISOString();let q=await s.from('processing_jobs').update({status,stage:'preview',stage_label:reviewCount?'Preview sẵn sàng • cần giáo viên duyệt':'Preview sẵn sàng',progress:100,message:reviewCount?`Đã xử lý xong; còn ${reviewCount} mục cần duyệt.`:'Đã xử lý xong; sẵn sàng xuất bản.',report,issues,review_count:reviewCount,blocking_issues:blocking,preview_path:b.preview_path,preview_url:previewUrl,result_json_path:b.result_json_path||'',pdf_path:b.pdf_path||'',updated_at:now}).eq('id',id).select('*').single();if(q.error)throw q.error;const j=q.data;const existing=await s.from('lessons').select('*').eq('lesson_id',j.lesson_id).maybeSingle();if(existing.error)throw existing.error;const lessonRow={lesson_id:j.lesson_id,title:j.lesson_title||j.lesson_id,grade:j.grade,chapter:j.chapter,lesson_number:j.lesson_number,published:existing.data?.published||false,publish_url:existing.data?.publish_url||null,storage_url:existing.data?.storage_url||null,preview_url:previewUrl,current_job_id:j.id,updated_at:now};q=await s.from('lessons').upsert(lessonRow,{onConflict:'lesson_id'});if(q.error)throw q.error;return json(res,200,{status,review_count:reviewCount,blocking_issues:blocking,preview_url:previewUrl})}catch(e){return json(res,500,{message:e.message})}}
async function processorFail(req,res){if(!allowMethod(req,res,['POST'])||!requireProcessor(req,res))return;try{const b=getBody(req),s=supabase();const {error}=await s.from('processing_jobs').update({status:'failed',message:String(b.message||'Lỗi xử lý').slice(0,1000),error_detail:String(b.detail||'').slice(-30000),updated_at:new Date().toISOString()}).eq('id',b.job_id);if(error)throw error;return json(res,200,{ok:true})}catch(e){return json(res,500,{message:e.message})}}
async function aiNotConfigured(req,res){return json(res,501,{message:'AI proxy chưa cấu hình trên Vercel. AI xử lý tài liệu chạy trên Windows Processor.'})}

const routes={
  'auth-login':authLogin,'auth-logout':authLogout,'health':health,
  'create-upload':createUpload,'complete-upload':completeUpload,'job':job,
  'lesson':lesson,'lessons':lessons,'review':review,'review-resolve':reviewResolve,
  'publish':publish,'processor-claim':processorClaim,'processor-heartbeat':processorHeartbeat,
  'processor-progress':processorProgress,'processor-result-upload':processorResultUpload,
  'processor-complete':processorComplete,'processor-fail':processorFail,
  'ai/openai':aiNotConfigured,'ai/gemini':aiNotConfigured,'ai/provider':aiNotConfigured
};

module.exports=async(req,res)=>{
  const r=routeName(req);
  const fn=routes[r];
  if(!fn)return json(res,404,{message:`API không tồn tại: ${r||'(trống)'}`});
  try{return await fn(req,res)}catch(e){return json(res,500,{message:e?.message||'Lỗi máy chủ'})}
};
